name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug - Show files before replacement
        run: |
          echo "=== Files containing placeholder ==="
          grep -r "REPLACE_WITH_YOUR_API_KEY" . || echo "No placeholder found"
        
      - name: Replace API key in HTML files
        run: |
          find . -name "*.html" -type f -exec sed -i 's/REPLACE_WITH_YOUR_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g' {} +
          
      - name: Debug - Verify replacement worked
        run: |
          echo "=== Checking if replacement worked ==="
          grep -r "REPLACE_WITH_YOUR_API_KEY" . && echo "ERROR: Placeholder still found!" || echo "SUCCESS: All placeholders replaced"
          echo "=== Checking for actual API key ==="
          grep -r "AIza" . && echo "API key found in files" || echo "No API key found"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4